[component]
structures = [ "content_blocks" ]
label = "Hero"
description = "Dummy"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
title = "Hi there, I am Tushar Gogna"
description_html = "<strong>Mobile Application Developer</strong> and <strong>Team Lead</strong> from Ontario, Canada. I work as an Android developer and have over 9 years of experience in the domain. I have worked independently as well as with Fortune 500 company (FIS) in the past. I am comfortable working in any setting as I am very adapting. My expertise is in Kotlin, Core Java, Android Jetpack components, JUnit and MVVM architecture."
image = "/images/01.jpg"
image_alt = "Tushar Gogna's picture"
cta_button = "Get in touch"
cta_button_link = "#contact"
works_button = "See my works"
works_button_link = "#projects"